package com.boaglio.watchdown.render;

import com.boaglio.watchdown.download.Chapter;
import com.boaglio.watchdown.download.VideoMetadata;
import com.boaglio.watchdown.summarize.KeyPoint;
import com.boaglio.watchdown.summarize.Section;
import com.boaglio.watchdown.summarize.Summary;
import com.boaglio.watchdown.transcribe.Segment;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.Clock;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;

/**
 * Writes the output folder described in AGENTS.md section 7.
 *
 * <p>The output is deterministic apart from {@code generated_at}, which comes from the injected
 * clock so that golden-file tests can pin it. Each file is written to a temporary file and then
 * moved into place, so a failed run never leaves a half-written folder that looks complete.
 */
public class MarkdownRenderer {

    private final Clock clock;

    public MarkdownRenderer(Clock clock) {
        this.clock = clock;
    }

    /** Writes the folder for one video and returns its path. */
    public Path render(RenderRequest request, Path outputRoot) {
        VideoMetadata metadata = request.metadata();
        Path folder = outputRoot.resolve(Slugs.slugify(metadata.title()) + "-" + metadata.id());
        try {
            Files.createDirectories(folder);
            writeAtomically(folder.resolve("transcript.md"), transcript(request));
            if (request.hasSummary()) {
                writeAtomically(folder.resolve("summary.md"), summary(request));
            } else {
                Files.deleteIfExists(folder.resolve("summary.md"));
            }
            writeAtomically(folder.resolve("AGENTS.md"), agents(request));
        } catch (IOException e) {
            throw new UncheckedIOException("cannot write " + folder, e);
        }
        return folder;
    }

    public String agents(RenderRequest request) {
        VideoMetadata metadata = request.metadata();
        double duration = metadata.durationSeconds();
        StringBuilder out = new StringBuilder();

        out.append("# AGENTS.md — ").append(Markdown.escape(metadata.title())).append("\n\n");
        out.append("Agent-readable digest of the YouTube video **").append(Markdown.escape(metadata.title()))
                .append("** by **").append(Markdown.escape(metadata.channel())).append("**\n(")
                .append(Timestamps.duration(metadata.durationSeconds()));
        if (metadata.uploadDate() != null) {
            out.append(", published ").append(metadata.uploadDate());
        }
        out.append("): ").append(metadata.webpageUrl()).append("\n\n");

        out.append("## How to use this folder\n\n");
        out.append("- `summary.md`: section-by-section summary with timestamp links.\n");
        out.append("- `transcript.md`: full transcript. **This is the source of truth.**\n");
        out.append("- The summaries were generated by a local LLM and may contain mistakes.\n");
        out.append("  Check anything important against `transcript.md` before relying on it.\n");
        out.append("- When citing this video, use timestamp links (`[mm:ss](url&t=Ns)`).\n\n");

        if (request.hasSummary()) {
            Summary summary = request.summary();
            out.append("## TL;DR\n\n").append(Markdown.escape(summary.tldr())).append("\n\n");
            out.append("## Key points\n\n");
            if (summary.keyPoints().isEmpty()) {
                out.append("_The model returned no key points._\n\n");
            } else {
                for (KeyPoint point : summary.keyPoints()) {
                    out.append("- ").append(Markdown.escape(point.text())).append(" (")
                            .append(Timestamps.link(metadata.id(), point.timestamp(), duration))
                            .append(")\n");
                }
                out.append('\n');
            }
        } else {
            out.append("## TL;DR\n\n");
            out.append("_No summary is available for this video._\n\n");
            out.append("Summarization failed: ").append(Markdown.escape(request.summaryFailure()))
                    .append("\nThe transcript in `transcript.md` is complete and usable.\n\n");
        }

        out.append("## Provenance\n\n");
        out.append(table(List.of(
                List.of("Field", "Value"),
                List.of("Video ID", metadata.id()),
                List.of("Language", request.transcript().language()),
                List.of("Transcribed", "`" + request.transcriptSource() + "`"),
                List.of("Summarized", request.hasSummary()
                        ? "ollama `" + request.ollamaModel() + "`"
                        : "failed"),
                List.of("Generated", generatedAt()),
                List.of("Tool", "watchdown " + request.toolVersion()))));
        return out.toString();
    }

    public String summary(RenderRequest request) {
        VideoMetadata metadata = request.metadata();
        Summary summary = request.summary();
        double duration = metadata.durationSeconds();

        StringBuilder out = new StringBuilder();
        frontMatter(out, request);
        out.append("# ").append(Markdown.escape(summary.title())).append("\n\n");
        out.append(Markdown.escape(summary.tldr())).append("\n\n");

        if (summary.sections().isEmpty()) {
            out.append("_The model returned no sections._\n");
            return out.toString();
        }
        for (Section section : summary.sections()) {
            out.append("## ").append(Markdown.escape(section.title())).append(" (")
                    .append(Timestamps.link(metadata.id(), section.start(), duration)).append(")\n\n");
            out.append(Markdown.escape(section.summary())).append("\n\n");
        }
        return out.toString().stripTrailing() + "\n";
    }

    public String transcript(RenderRequest request) {
        VideoMetadata metadata = request.metadata();
        double duration = metadata.durationSeconds();
        List<Chapter> chapters = metadata.chapters();

        StringBuilder out = new StringBuilder();
        frontMatter(out, request);
        out.append("# Transcript — ").append(Markdown.escape(metadata.title())).append("\n\n");

        int nextChapter = 0;
        for (Segment segment : request.transcript().segments()) {
            while (nextChapter < chapters.size() && segment.start() >= chapters.get(nextChapter).start()) {
                if (!out.toString().endsWith("\n\n")) {
                    out.append('\n');
                }
                out.append("## ").append(Markdown.escape(chapters.get(nextChapter).title())).append("\n\n");
                nextChapter++;
            }
            out.append("**").append(Timestamps.link(metadata.id(), segment.start(), duration)).append("** ")
                    .append(Markdown.escape(segment.text())).append('\n');
        }
        return out.toString().stripTrailing() + "\n";
    }

    private void frontMatter(StringBuilder out, RenderRequest request) {
        VideoMetadata metadata = request.metadata();
        out.append("---\n");
        out.append("title: ").append(Markdown.yaml(metadata.title())).append('\n');
        out.append("channel: ").append(Markdown.yaml(metadata.channel())).append('\n');
        out.append("url: ").append(Markdown.yaml(metadata.webpageUrl())).append('\n');
        out.append("video_id: ").append(Markdown.yaml(metadata.id())).append('\n');
        out.append("duration_seconds: ").append(metadata.durationSeconds()).append('\n');
        out.append("published: ").append(Markdown.yaml(
                metadata.uploadDate() == null ? "" : metadata.uploadDate().toString())).append('\n');
        out.append("language: ").append(Markdown.yaml(request.transcript().language())).append('\n');
        out.append("generated_at: ").append(Markdown.yaml(generatedAt())).append('\n');
        out.append("---\n\n");
    }

    private String generatedAt() {
        return Instant.now(clock).truncatedTo(ChronoUnit.SECONDS).toString();
    }

    /** A Markdown table whose columns are as wide as their widest cell, header row first. */
    private static String table(List<List<String>> rows) {
        int columns = rows.getFirst().size();
        int[] widths = new int[columns];
        for (List<String> row : rows) {
            for (int column = 0; column < columns; column++) {
                widths[column] = Math.max(widths[column], row.get(column).length());
            }
        }

        StringBuilder out = new StringBuilder();
        appendRow(out, rows.getFirst(), widths);
        out.append('|');
        for (int width : widths) {
            out.append("-".repeat(width + 2)).append('|');
        }
        out.append('\n');
        rows.stream().skip(1).forEach(row -> appendRow(out, row, widths));
        return out.toString();
    }

    private static void appendRow(StringBuilder out, List<String> row, int[] widths) {
        out.append('|');
        for (int column = 0; column < row.size(); column++) {
            out.append(' ').append(pad(row.get(column), widths[column])).append(" |");
        }
        out.append('\n');
    }

    private static String pad(String value, int width) {
        return value.length() >= width ? value : value + " ".repeat(width - value.length());
    }

    /** Writes through a temporary file so that an interrupted run leaves no half-written file. */
    private static void writeAtomically(Path target, String content) throws IOException {
        Path temporary = Files.createTempFile(target.getParent(), ".watchdown-", ".tmp");
        try {
            Files.writeString(temporary, content, StandardCharsets.UTF_8);
            try {
                Files.move(temporary, target, StandardCopyOption.REPLACE_EXISTING,
                        StandardCopyOption.ATOMIC_MOVE);
            } catch (java.nio.file.AtomicMoveNotSupportedException e) {
                Files.move(temporary, target, StandardCopyOption.REPLACE_EXISTING);
            }
        } finally {
            Files.deleteIfExists(temporary);
        }
    }
}
